/* THIS HEADER IS AUTOGENERATED. DO NOT EDIT.
 * Internal header. do not include in clients of RVM. */
#ifndef _OPCODES_H_
#define _OPCODES_H_

#define MOV            ((opcode_t) (0))
#define CALL_UPVAR     ((opcode_t) (1))
#define CALL_REG       ((opcode_t) (2))
#define CLOSE          ((opcode_t) (3))
#define JUMP           ((opcode_t) (4))
#define TAILCALL_UPVAR ((opcode_t) (5))
#define TAILCALL_REG   ((opcode_t) (6))

#endif
